--1
CREATE OR REPLACE VIEW v_TotalPedido AS
SELECT 
CLI.COD_CLI, 
PED.NRO_PED,
SUM(MOV.TOTAL_MOV) TOTAL_MOV
FROM MOVIMENTO MOV
INNER JOIN PEDIDO PED ON PED.NRO_PED = MOV.NRO_PED
INNER JOIN CLIENTE CLI ON CLI.COD_CLI = PED.COD_CLI
GROUP BY
CLI.COD_CLI, 
PED.NRO_PED;

--2
CREATE OR REPLACE FUNCTION atualizarTotalPedido(
    char(10),
	char(10)
) RETURNS SETOF PEDIDO AS
$$

UPDATE PEDIDO
SET TOTAL_PED = (SELECT TOTAL_MOV FROM v_TotalPedido WHERE COD_CLI = $1)
WHERE COD_CLI = $1
AND NRO_PED = $2;

--TERMINO DA FUNÇÃO
SELECT * 
FROM PEDIDO
WHERE COD_CLI = $1
AND NRO_PED = $2;

$$
LANGUAGE SQL;
