CREATE OR REPLACE FUNCTION FN_EXEMPLO_TEMP_TABLE( ) RETURNS VARCHAR(10) AS
$$
BEGIN
-- CRIAÇÃO DE TABELA TEMPORÁRIA. EXISTE APENAS DURANTE A CONEXÃO DO USUÁRIO
CREATE TEMP TABLE TMP_CLIENTE (COD_CLI CHAR(10), NOME CHAR(40));

INSERT INTO TMP_CLIENTE
SELECT
COD_CLI, NOME
FROM
CLIENTE
WHERE
COD_CLI = 'c1';

--FAZ ALGO AQUI A PARTIR DOS CODIGOS DO COD_CLI 1

DROP TABLE TMP_CLIENTE;

RETURN 'FIM';

END;
$$
LANGUAGE PLPGSQL;

SELECT * FROM FN_EXEMPLO_TEMP_TABLE();

SELECT * FROM TMP_CLIENTE;