-- JOIN
SELECT
DISTINCT MOVI.COD_PROD, PROD.NOME
FROM PRODUTO PROD
INNER JOIN MOVIMENTO MOVI ON MOVI.COD_PROD = PROD.COD_PROD

-- IN
SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE PROD.COD_PROD IN (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI 
)

-- EXISTIS
SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE EXISTS (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI
	WHERE PROD.COD_PROD = MOVI.COD_PROD
)