-- JOIN
SELECT
DISTINCT MOVI.COD_PROD, PROD.NOME
FROM PRODUTO PROD
INNER JOIN MOVIMENTO MOVI ON MOVI.COD_PROD = PROD.COD_PROD

-- IN
SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE PROD.COD_PROD IN (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI 
)

-- EXISTIS
SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE EXISTS (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI
	WHERE PROD.COD_PROD = MOVI.COD_PROD
)

-- INTERSECT SÓ O QUE É COMUM
SELECT 
PROD.NOME 
FROM PRODUTO PROD

INTERSECT

SELECT
DISTINCT PROD.NOME
FROM PRODUTO PROD
INNER JOIN MOVIMENTO MOVI ON MOVI.COD_PROD = PROD.COD_PROD

-- CONSULTAS NEGATIVAS
SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE PROD.COD_PROD NOT IN (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI 
)

SELECT
PROD.NOME
FROM PRODUTO PROD
WHERE NOT EXISTS (
	SELECT 
	MOVI.COD_PROD
	FROM MOVIMENTO MOVI
	WHERE PROD.COD_PROD = MOVI.COD_PROD
)

SELECT 
PROD.NOME 
FROM PRODUTO PROD

EXCEPT

SELECT
DISTINCT PROD.NOME
FROM PRODUTO PROD
INNER JOIN MOVIMENTO MOVI ON MOVI.COD_PROD = PROD.COD_PROD

